openapi: 3.0.1
info:
  title: Troubles API
  version: "1.0.0"
servers:
  - url: https://{apiId}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      apiId:
        default: "your-api-id"
      region:
        default: "ap-northeast-1"
      stage:
        default: "Prod"
paths:
  /troubles:
    get:
      operationId: getTroubles
      summary: 投稿された困りごと一覧を取得
      security:
        - CognitoAuthorizer: []
      responses:
        '200':
          description: 一覧
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTroubles'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバ内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      operationId: createTrouble
      summary: 新しい困りごとを投稿
      security:
        - CognitoAuthorizer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TroubleInput'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TroubleCreationResponse'
        '400':
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバ内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    CognitoAuthorizer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "内部エラーが発生しました"
        error:
          type: string
          example: "InternalServerError"
    TroubleInput:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "毎回VPNつなぐのめんどい"
        category:
          type: string
          example: "ネットワーク"
    Trouble:
      allOf:
        - $ref: '#/components/schemas/TroubleInput'
        - type: object
          properties:
            id:
              type: string
              example: "abc-123"
    PaginatedTroubles:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Trouble'
        nextToken:
          type: string
          nullable: true
          example: "eyJpZCI6ICIxMjM0NTY3ODkwIn0="
          description: 次ページ取得用のトークン（存在しない場合はnull）
    TroubleCreationResponse:
      type: object
      properties:
        result:
          type: string
          example: "アイテムが作成されました"
        item:
          $ref: '#/components/schemas/Trouble'
