AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lecture9

  lecture9のサンプルSAMテンプレート

Parameters:
  Email:
    Type: String
    AllowedPattern: "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
    ConstraintDescription: 有効なメールアドレスを指定してください。

Resources:
  SNSHumanApprovalEmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Stock Trading Approval Topic

  SNSHumanApprovalEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSHumanApprovalEmailTopic
      Endpoint: !Ref Email

  ApproveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/approve/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        Approve:
          Type: Api
          Properties:
            Path: /approve
            Method: get

  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/approval_step.asl.json
      DefinitionSubstitutions:
        SNSHumanApprovalEmailTopic: !Ref SNSHumanApprovalEmailTopic
        ApproveUrl: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/approve"
      Events: {}
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref StockCheckerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockSellerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockBuyerFunction
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionTable
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref SNSHumanApprovalEmailTopic
