version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lecture10-infrastructure"

s3_prefix = "lecture10-infrastructure"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DistributionDomainName=\"lecture10.example.com\""
image_repositories = []
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.build]
[default.build.parameters]
use_container = false 