AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lecture3

  Sample SAM Template for lecture3

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    Description: Environment
    Default: local
  KeywordTableName:
    Type: String
    Description: DynamoDB table name for the Keywords

Resources:
  RequirementsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: RequirementsLayer
      Description: Layer for Python requirements
      ContentUri: work/CommonLayer
      CompatibleRuntimes:
        - python3.13
    Metadata:
      BuildMethod: python3.13
  GetValidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref RequirementsLayer
      CodeUri: work/GetValidation/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SetKeyword:
          Type: Api
          Properties:
            Path: /work
            Method: get
  PutValidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref RequirementsLayer
      CodeUri: work/PutValidation/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SetKeyword:
          Type: Api
          Properties:
            Path: /work
            Method: put
  DeleteValidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref RequirementsLayer
      CodeUri: work/DeleteValidation/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SetKeyword:
          Type: Api
          Properties:
            Path: /work/{user_id}
            Method: delete
  StoreFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: keyword/store/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: keyword-store
          ENDPOINT_URL: http://host.docker.internal:4566
      Policies:
        - DynamoDBCrudPolicy:
            TableName: keyword-store
      Events:
        SetKeyword:
          Type: Api
          Properties:
            Path: /keyword
            Method: post
  DescribeStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: keyword/describe/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: keyword-store
          ENDPOINT_URL: http://host.docker.internal:4566
      Policies:
        - DynamoDBCrudPolicy:
            TableName: keyword-store
      Events:
        ListKeyword:
          Type: Api
          Properties:
            Path: /keyword
            Method: get
  GetKeywordByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: keyword/get/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: keyword-store
          ENDPOINT_URL: http://host.docker.internal:4566
      Policies:
        - DynamoDBCrudPolicy:
            TableName: keyword-store
      Events:
        GetKeyword:
          Type: Api
          Properties:
            Path: /keyword/{id}
            Method: get
